# This is a basic workflow to help you get started with Actions

name: Auto-update

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:
jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - name: Make build timestamp
        id: build-ts
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%s')"
      - name: Perform build
        run: |
          sudo apt update && sudo apt install --no-install-recommends -y jq
          source source-update/merge-rat.sh
          git branch -D auto-build || true
          git branch auto-build
      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Promote updated data
          branch: auto-build
          file_pattern: '*.json'
          skip_fetch: true
          skip_dirty_check: true
          push_options: '--force'
          commit_options: ' --allow-empty'
