name: Promote

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Perform build
        run: |
          git branch -D auto-build || true
          git branch auto-build
      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Promote updated data
          branch: auto-build
          file_pattern: '*.json'
          skip_fetch: true
          skip_dirty_check: true
          push_options: '--force'
