# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - name: Perform build
        run: |
          apt update && apt install --no-install-recommends -y jq
          source-update/merge-rat.sh
      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Update data
          branch: auto-build
          file_pattern: '*.json'        
